[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["07311631769 <douglas.siviotti@serpro.gov.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
